//! Generated files: build output and caches (`__pycache__/`,
//! `node_modules/`, …) that aivyx-coder's own change views hide and
//! `/commit` never auto-stages, matched with `.gitignore` semantics.
//!
//! The matcher here is pure — it says only whether a path *looks*
//! generated. Hiding applies to untracked paths alone (a file git already
//! tracks is always shown, exactly as `.gitignore` never hides a tracked
//! file), and that check belongs to the caller, using [`tracked_paths`].

use std::collections::HashSet;
use std::path::Path;

use ignore::gitignore::{Gitignore, GitignoreBuilder};

/// The default `[git] ignore` patterns, in `.gitignore` syntax.
pub const DEFAULT_GENERATED_PATTERNS: &[&str] = &[
    "__pycache__/",
    "*.pyc",
    "*.pyo",
    ".pytest_cache/",
    ".mypy_cache/",
    ".ruff_cache/",
    "node_modules/",
    ".venv/",
    ".DS_Store",
];

/// [`DEFAULT_GENERATED_PATTERNS`] as owned strings.
pub fn default_generated_patterns() -> Vec<String> {
    DEFAULT_GENERATED_PATTERNS
        .iter()
        .map(|p| p.to_string())
        .collect()
}

/// A `.gitignore`-semantics matcher over a fixed pattern list, rooted at
/// a repository's top level.
pub struct GeneratedFiles {
    matcher: Gitignore,
}

impl GeneratedFiles {
    /// Builds the matcher from `patterns` (one `.gitignore` line each),
    /// rooted at `root`. A pattern `.gitignore` itself couldn't parse is
    /// skipped, so one bad entry never disables the rest.
    pub fn new(root: &Path, patterns: &[String]) -> Self {
        let mut builder = GitignoreBuilder::new(root);
        for pattern in patterns {
            let _ = builder.add_line(None, pattern);
        }
        let matcher = builder.build().unwrap_or_else(|_| Gitignore::empty());
        Self { matcher }
    }

    /// Whether `rel_path` (relative to the root, `/`-separated, as git
    /// prints it) is a generated file: the path itself or any directory
    /// above it matches, with negations (`!keep.pyc`) honoured.
    pub fn is_generated(&self, rel_path: &str) -> bool {
        let path = Path::new(rel_path);
        // The matcher panics on a path outside its root; a relative path
        // never is, and nothing absolute is ever generated by this rule.
        if rel_path.is_empty() || path.has_root() {
            return false;
        }
        self.matcher
            .matched_path_or_any_parents(path, false)
            .is_ignore()
    }
}

/// Every path git tracks in the repository whose top level is `root`,
/// relative to it (`git ls-files -z`, through the hardened [`crate::run_git`]).
pub async fn tracked_paths(root: &Path) -> Result<HashSet<String>, String> {
    let out = crate::run_git(root, &["ls-files", "-z"], &[]).await?;
    Ok(out
        .split('\0')
        .filter(|p| !p.is_empty())
        .map(str::to_string)
        .collect())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn matcher(patterns: &[&str]) -> GeneratedFiles {
        let patterns: Vec<String> = patterns.iter().map(|p| p.to_string()).collect();
        GeneratedFiles::new(Path::new("/repo"), &patterns)
    }

    #[test]
    fn default_patterns_match_like_gitignore() {
        let files = GeneratedFiles::new(Path::new("/repo"), &default_generated_patterns());
        for (path, expected) in [
            ("a/b/__pycache__/x.pyc", true),
            ("__pycache__/m.cpython-312.pyc", true),
            ("node_modules/pkg/index.js", true),
            ("web/node_modules/pkg/index.js", true),
            ("foo.pyc", true),
            ("pkg/foo.pyo", true),
            (".pytest_cache/v/cache/nodeids", true),
            (".venv/bin/python", true),
            ("sub/.DS_Store", true),
            ("src/x.py", false),
            ("README.md", false),
            ("node_modules_notes.txt", false),
            ("src/__pycache__.rs", false),
            ("", false),
            ("/abs/__pycache__/x.pyc", false),
        ] {
            assert_eq!(files.is_generated(path), expected, "{path}");
        }
    }

    #[test]
    fn a_negation_pattern_keeps_a_file() {
        let files = matcher(&["*.pyc", "!keep.pyc"]);
        assert!(files.is_generated("drop.pyc"));
        assert!(!files.is_generated("keep.pyc"));
        assert!(!files.is_generated("sub/keep.pyc"));
    }

    #[test]
    fn an_empty_list_matches_nothing() {
        let files = matcher(&[]);
        for path in ["__pycache__/x.pyc", "node_modules/a.js", "foo.pyc"] {
            assert!(!files.is_generated(path), "{path}");
        }
    }

    #[test]
    fn a_bad_pattern_does_not_disable_the_rest() {
        let files = matcher(&["[", "*.pyc"]);
        assert!(files.is_generated("x.pyc"));
    }

    #[tokio::test]
    async fn tracked_paths_lists_the_index_from_the_root() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        for args in [
            vec!["init", "-q"],
            vec!["config", "user.name", "t"],
            vec!["config", "user.email", "t@t.invalid"],
        ] {
            crate::run_git(root, &args, &[]).await.unwrap();
        }
        std::fs::create_dir(root.join("sub")).unwrap();
        std::fs::write(root.join("sub/a b.txt"), "x").unwrap();
        std::fs::write(root.join("top.txt"), "x").unwrap();
        std::fs::write(root.join("untracked.txt"), "x").unwrap();
        crate::run_git(root, &["add", "sub/a b.txt", "top.txt"], &[])
            .await
            .unwrap();
        let tracked = tracked_paths(root).await.unwrap();
        let expected: HashSet<String> = ["sub/a b.txt", "top.txt"]
            .iter()
            .map(|s| s.to_string())
            .collect();
        assert_eq!(tracked, expected);
    }
}
